### ISSUE TITLE
I'm getting an error while trying to deploy

### ISSUE THREAD

**Issue by Avien** [msc654/webpack-salesforce-deploy#6]
![image](https://cloud.githubusercontent.com/assets/4569044/16557774/62949474-41ea-11e6-97ee-4fba90a980da.png)

Error: Invalid URI "/services/Soap/m/36.0"
from script:  conn.metadata.upsert('StaticResource', metaDataPayload, function (err, results) {

Any ideas?
Thanks

**Comment by celador** [comment]
Hello @Avien Can you try now?  We merged a PR yesterday that should resolve the issue

**Comment by Avien** [comment]
It seems I didn't define a token in the config which was concatenated as undefined with the password
But that didn't solve the problem as well so I eventually installed gulp-jsforce-deploy plugin
Thanks anyway

**Comment by msc654** [comment]
Changes have been published to npm. Apologies for the out of sync update.
